//Get user list
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILED = "GET_USER_LIST_FAILED";

//Delete user list
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//Change user role
export const CHANGE_USER_ROLE_SUCCESS = "CHANGE_USER_ROLE_SUCCESS";
export const CHANGE_USER_ROLE_LOADING = "CHANGE_USER_ROLE_LOADING";
export const CHANGE_USER_ROLE_FAILED = "CHANGE_USER_ROLE_FAILED";