//Create sub category
export const CREATE_SUB_CATEGORY_LOADING = "CREATE_SUB_CATEGORY_LOADING";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAILED = "CREATE_SUB_CATEGORY_FAILED";

// Get sub category
export const GET_ALL_SUB_CATEGORY_SUCCESS = "GET_ALL_SUB_CATEGORY_SUCCESS";
export const GET_ALL_SUB_CATEGORY_FAILED = "GET_ALL_SUB_CATEGORY_FAILED";


//Delete sub category
export const DELETE_SUB_CATEGORY_LOADING = "DELETE_SUB_CATEGORY_LOADING";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAILED = "DELETE_SUB_CATEGORY_FAILED";

//GET single sub category
export const GET_SINGLE_SUB_CATE_SUCCESS = "GET_SINGLE_SUB_CATE_SUCCESS";
export const GET_SINGLE_SUB_CATE_FAILED = "GET_SINGLE_SUB_CATE_FAILED";

//Update sub category
export const UPDATE_SUB_CATEGORY_LOADING = "UPDATE_SUB_CATEGORY_LOADING";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAILED = "UPDATE_SUB_CATEGORY_FAILED";