//Create Products
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_LOADING = "CREATE_PRODUCTS_LOADING";
export const CREATE_PRODUCTS_FAILED = "CREATE_PRODUCTS_FAILED";

//Get Products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

//Delete Products
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_LOADING = "DELETE_PRODUCTS_LOADING";
export const DELETE_PRODUCTS_FAILED = "DELETE_PRODUCTS_FAILED";

//Get single Products
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAILED = "GET_SINGLE_PRODUCTS_FAILED";

//Update products
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCTS_LOADING = "UPDATE_PRODUCTS_LOADING";
export const UPDATE_PRODUCTS_FAILED = "UPDATE_PRODUCTS_FAILED";