//User Login Constant
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";

//User Password Reset Request Constant
export const PASSWORD_RESET_LOADING = "PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

//New Password Constant
export const NEW_PASSWORD_LOADING = "NEW_PASSWORD_LOADING";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAILED = "NEW_PASSWORD_FAILED";

//Get Profile Constant
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";