//Create tag
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_LOADING = "CREATE_TAG_LOADING";
export const CREATE_TAG_FAILED = "CREATE_TAG_FAILED";

//Get Tags
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAILED = "GET_TAGS_FAILED";

//Delete Tags
export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS";
export const DELETE_TAGS_LOADING = "DELETE_TAGS_LOADING";
export const DELETE_TAGS_FAILED = "DELETE_TAGS_FAILED";

//Get Single tags
export const GET_SINGLE_TAG_SUCCESS = "GET_SINGLE_TAG_SUCCESS";
export const GET_SINGLE_TAG_FAILED = "GET_SINGLE_TAG_FAILED";

//Update tags
export const UPDATE_TAGS_SUCCESS = "UPDATE_TAGS_SUCCESS";
export const UPDATE_TAGS_FAILED = "UPDATE_TAGS_FAILED";
export const UPDATE_TAGS_LOADING = "UPDATE_TAGS_LOADING";