//Create banners
export const CREATE_BANNERS_SUCCESS = "CREATE_BANNERS_SUCCESS";
export const CREATE_BANNERS_LOADING = "CREATE_BANNERS_LOADING";
export const CREATE_BANNERS_FAILED = "CREATE_BANNERS_FAILED";

//Create sliders
export const CREATE_SLIDERS_SUCCESS = "CREATE_SLIDERS_SUCCESS";
export const CREATE_SLIDERS_LOADING = "CREATE_SLIDERS_LOADING";
export const CREATE_SLIDERS_FAILED = "CREATE_SLIDERS_FAILED";

//Create sliders
export const CREATE_GALLERY_SUCCESS = "CREATE_GALLERY_SUCCESS";
export const CREATE_GALLERY_LOADING = "CREATE_GALLERY_LOADING";
export const CREATE_GALLERY_FAILED = "CREATE_GALLERY_FAILED";

//Get banners
export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS";
export const GET_BANNERS_FAILED = "GET_BANNERS_FAILED";

//Get banners
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAILED = "GET_GALLERY_FAILED";

//Get sliders
export const GET_SLIDERS_SUCCESS = "GET_SLIDERS_SUCCESS";
export const GET_SLIDERS_FAILED = "GET_SLIDERS_FAILED";

//Delete banners
export const DELETE_BANNERS_SUCCESS = "DELETE_BANNERS_SUCCESS";
export const DELETE_BANNERS_LOADING = "DELETE_BANNERS_LOADING";
export const DELETE_BANNERS_FAILED = "DELETE_BANNERS_FAILED";

//Delete banners
export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_LOADING = "DELETE_GALLERY_LOADING";
export const DELETE_GALLERY_FAILED = "DELETE_GALLERY_FAILED";

//Delete sliders
export const DELETE_SLIDERS_SUCCESS = "DELETE_SLIDERS_SUCCESS";
export const DELETE_SLIDERS_LOADING = "DELETE_SLIDERS_LOADING";
export const DELETE_SLIDERS_FAILED = "DELETE_SLIDERS_FAILED";

//Get Sections
export const GET_ALL_SECTIONS_SUCCESS = "GET_ALL_SECTIONS_SUCCESS";
export const GET_ALL_SECTIONS_FAILED = "GET_ALL_SECTIONS_FAILED";

//Get single sections
export const GET_SINGLE_SEC_SUCCESS = "GET_SINGLE_SEC_SUCCESS";
export const GET_SINGLE_SEC_FAILED = "GET_SINGLE_SEC_FAILED";

//Update sections
export const UPDATE_SECTIONS_SUCCESS = "UPDATE_SECTIONS_SUCCESS";
export const UPDATE_SECTIONS_LOADING = "UPDATE_SECTIONS_LOADING";
export const UPDATE_SECTIONS_FAILED = "UPDATE_SECTIONS_FAILED";


export const ADD_SECTIONS_LOADING = "ADD_SECTIONS_LOADING";
export const ADD_SECTIONS_FAILED = "ADD_SECTIONS_FAILED";
export const ADD_SECTIONS_SUCCESS = "ADD_SECTIONS_SUCCESS";