//Create Brand
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_LOADING = "CREATE_BRAND_LOADING";
export const CREATE_BRAND_FAILED = "CREATE_BRAND_FAILED";

//Get Brand
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILED = "GET_BRAND_FAILED";

//Delete Brand
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_LOADING = "DELETE_BRAND_LOADING";
export const DELETE_BRAND_FAILED = "DELETE_BRAND_FAILED";

//Get Single Brand
export const GET_SINGLE_BRAND_SUCCESS = "GET_SINGLE_BRAND_SUCCESS";
export const GET_SINGLE_BRAND_FAILED = "GET_SINGLE_BRAND_FAILED";

//Update Brand
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_LOADING = "UPDATE_BRAND_LOADING";
export const UPDATE_BRAND_FAILED = "UPDATE_BRAND_FAILED";