//Create attribute
export const CREATE_ATTRIBUTE_SUCCESS = "CREATE_ATTRIBUTE_SUCCESS";
export const CREATE_ATTRIBUTE_LOADING = "CREATE_ATTRIBUTE_LOADING";
export const CREATE_ATTRIBUTE_FAILED = "CREATE_ATTRIBUTE_FAILED";

//Get Attributes
export const GET_ATTRIBUTES_SUCCESS = "GET_ATTRIBUTES_SUCCESS";
export const GET_ATTRIBUTES_FAILED = "GET_ATTRIBUTES_FAILED";

//Delete attributes
export const DELETE_ATTRIBUTES_LOADING = "DELETE_ATTRIBUTES_LOADING";
export const DELETE_ATTRIBUTES_SUCCESS = "DELETE_ATTRIBUTES_SUCCESS";
export const DELETE_ATTRIBUTES_FAILED = "DELETE_ATTRIBUTES_FAILED";

//Get single attribute
export const GET_SINGLE_ATTR_SUCCESS = "GET_SINGLE_ATTR_SUCCESS";
export const GET_SINGLE_ATTR_FAILED = "GET_SINGLE_ATTR_FAILED";

//Update attribute
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS";
export const UPDATE_ATTRIBUTE_LOADING = "UPDATE_ATTRIBUTE_LOADING";
export const UPDATE_ATTRIBUTE_FAILED = "UPDATE_ATTRIBUTE_FAILED";